# Generated by Django 2.2 on 2019-04-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_shorten',
            name='original_link',
            field=models.CharField(max_length=400),
        ),
    ]
